Repository Mayur-Pagote/README_Design_Kit, pull requests merged in 2025-06, with the labels that each got.

#41 Starter Drag drop editor created #9
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/DraggableElement.tsx
  src/components/EditorCanvas.tsx
  src/components/ElementEditor.tsx
  src/components/ElementPalette.tsx
  src/components/ElementRenderer.tsx
  src/components/ReadmePreview.tsx
  src/components/SimpleDraggableElement.tsx
  src/config/elements.ts
  src/data/demo.ts
  src/pages/DragDropEditor.tsx
  src/types/elements.ts
Labels: SSOC S4, ADVANCED

#50 Added favicon and meta-tags
  index.html
  public/Assets/android-chrome-192x192.png
  public/Assets/android-chrome-512x512.png
  public/Assets/apple-touch-icon.png
  public/Assets/favicon-16x16.png
  public/Assets/favicon-32x32.png
  public/Assets/favicon.ico
  public/Assets/site.webmanifest
Labels: SSOC S4, BEGINNER

#53 graphs now update in real-time when GitHub username changes
  src/components/PreviewGrid.tsx
Labels: SSOC S4, BEGINNER

#63 Logo update
  rdk.svg
  rdkt.svg
  src/components/Footer.tsx
  src/components/Navbar.tsx
Labels: SSOC S4, BEGINNER

#66 issue #36 resolved
  src/pages/Home.tsx
Labels: SSOC S4, BEGINNER

#70 Improve Logo
  index.html
  rdkf.svg
  src/components/Footer.tsx
  src/components/Navbar.tsx
Labels: SSOC S4, BEGINNER

#73 More Content
  READMEelements.md
  public/Assets/Shocked.png
  public/Assets/Smiling.png
  public/Assets/Yawn.png
  public/Assets/discord-1.png
  public/Assets/discord.gif
  public/Assets/facebook-1.png
  public/Assets/facebook.gif
  public/Assets/instagram-1.webp
  public/Assets/instagram.gif
  public/Assets/linkedin-1.png
  public/Assets/linkedin.gif
  public/Assets/notinterested.png
  public/Assets/sleeping.png
  public/Assets/smart.png
  public/Assets/upsidedown.png
Labels: SSOC S4, BEGINNER

#74 Added legal pages and content for privacy policy and terms of service
  src/App.tsx
  src/components/Footer.tsx
  src/components/legal/content/privacy-policy.ts
  src/components/legal/content/terms-of-service.ts
  src/pages/PrivacyPolicy.tsx
  src/pages/TermsOfService.tsx
  tsconfig.app.json
Labels: SSOC S4, BEGINNER

#79 fix: update community links in footer to correct URLs
  src/components/Footer.tsx
Labels: SSOC S4, BEGINNER

#82 Update issue templates
  .github/ISSUE_TEMPLATE/-bug-.md
  .github/ISSUE_TEMPLATE/-enhancement-.md
  .github/ISSUE_TEMPLATE/-feature-.md
Labels: SSOC S4, BEGINNER

#85 ci(server): PR-build-check
  .github/workflows/pr-build-check.yml
Labels: SSOC S4, INTERMEDIATE

#110 dark mode toggle updated #37 completed
  src/components/Navbar.tsx
  src/components/mode-toggle.tsx
  src/components/motion-provider.tsx
  src/index.css
  src/pages/Dashboard.tsx
  src/pages/Home.tsx
  src/theme/provider.tsx
  src/theme/toggler.tsx
  templatedetails.md
Labels: SSOC S4, BEGINNER

#121 Added the feature request page and updated the ComingSoon.tsx with a navigation button to the page
  README.md
  docs/feature-request.md
  src/App.tsx
  src/components/FeatureCard.tsx
  src/components/FeatureRequestForm.tsx
  src/hooks/useLocalStorage.ts
  src/pages/ComingSoon.tsx
  src/pages/FeatureRequestsPage.tsx
  src/types/FeatureRequest.ts
Labels: SSOC S4, INTERMEDIATE

#131 Mobile view enhancements
  src/components/Navbar.tsx
  src/pages/Elements.tsx
  src/pages/Home.tsx
Labels: SSOC S4, INTERMEDIATE

#134 [Enhancement] Applied Animated Gradient Background Ref Hero Section
  src/pages/Hero.tsx
Labels: SSOC S4, BEGINNER

#136 Added AI Branding Assistant in Drag & Drop Editor
  README.md
  src/components/AssistantLauncher.tsx
  src/components/BrandingAssistant.tsx
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/pages/DragDropEditor.tsx
  src/types/branding.ts
  src/types/elements.ts
  src/utils/brandingAnalyzer.ts
Labels: SSOC S4, INTERMEDIATE

#156 Feat/UI fixes
  package-lock.json
  src/App.tsx
  src/components/AssistantLauncher.tsx
  src/components/ExportImageTool.tsx
  src/components/ReadmePreview.tsx
  src/components/ScrollToTop.tsx
  src/pages/DragDropEditor.tsx
Labels: SSOC S4, INTERMEDIATE

#181 Bug fixes
  src/components/TemplatePreview.tsx
  src/pages/FeatureRequestsPage.tsx
Labels: SSOC S4, BEGINNER

#185 issue #135 resolved
  src/pages/Hero.tsx
Labels: SSOC S4, BEGINNER

#198 Made Drag and Drop page responsive
  src/pages/DragDropEditor.tsx
Labels: SSOC S4, INTERMEDIATE

#201 bug fixes and enhancement
  src/components/TemplateLibrary.tsx
  src/index.css
Labels: SSOC S4, BEGINNER

#203 Fix: UI/UX - Resolve Horizontal Scrollbar & 'Need Help' Section Issues
  package-lock.json
  src/components/QuickStartGuide.tsx
  src/index.css
  src/pages/Home.tsx
Labels: SSOC S4, BEGINNER
