Repository Mayur-Pagote/README_Design_Kit, pull requests merged in 2025-07, with the labels that each got.

#207 UI Enhancement
  src/components/1.svg
  src/components/2.svg
  src/components/3.svg
  src/components/4.svg
  src/components/5.svg
  src/components/6.svg
  src/components/TemplateThumbnail.tsx
  src/components/soon.svg
Labels: SSOC S4, BEGINNER

#215 Bug Fixes
  src/components/AssistantLauncher.tsx
  src/components/TemplateLibrary.tsx
  src/components/TemplateThumbnail.tsx
  src/pages/ComingSoon.tsx
  src/pages/DragDropEditor.tsx
Labels: SSOC S4, BEGINNER

#217 Added Sample Project
  src/components/ProjectCard.tsx
  src/components/ProjectsSection.tsx
Labels: SSOC S4, BEGINNER

#221 Update Submit Form
  src/components/ProjectCard.tsx
  src/components/ProjectsSection.tsx
  src/components/SubmitSection.tsx
Labels: SSOC S4, BEGINNER

#224 Bug Fixes and Enhancement
  src/components/ProjectCard.tsx
  src/components/ProjectsSection.tsx
  src/components/_components/footer.tsx
  src/components/_components/header.tsx
  src/components/generator/AboutMePage.tsx
  src/components/generator/AdditionalStuffPage.tsx
  src/components/generator/FinalPage.tsx
  src/components/generator/GitHubStatsPage.tsx
  src/components/generator/ProgressIndicator.tsx
  src/components/generator/Readme-generator.tsx
  src/components/generator/SocialLinksPage.tsx
  src/components/generator/TechStackPage.tsx
  src/components/generator/WelcomePage.tsx
  src/pages/FeatureRequestsPage.tsx
Labels: SSOC S4, BEGINNER

#223 AI README Generator with Live Chat, Gemini API, and Vibecoding-Style Templates
  package-lock.json
  package.json
  src/App.tsx
  src/components/AIEditorGuide.tsx
  src/components/Navbar.tsx
  src/components/readme-editor/APIKeySettings.tsx
  src/components/readme-editor/ChatPanel.tsx
  src/components/readme-editor/CodeEditor.tsx
  src/components/readme-editor/MarkdownPreview.tsx
  src/components/readme-editor/ReadmeEditor.tsx
  src/pages/AIEditorIntro.tsx
  src/pages/Home.tsx
  src/services/readmeAIService.ts
Labels: SSOC S4, ADVANCED

#232 Minor Bug Fix
  src/components/_components/header.tsx
Labels: SSOC S4, BEGINNER

#233 Enhanced AI Readme Editor
  src/components/readme-editor/ReadmeEditor.tsx
  src/pages/Home.tsx
Labels: SSOC S4, BEGINNER

#245 Bug Fix
  src/components/readme-editor/GitHubRepoAnalyzer.tsx
Labels: SSoC25, Beginner
